### ISSUE TITLE
Upgrade to .NET Core 2.1

### ISSUE THREAD

**Issue by sitwalkstand** [Microsoft/featurebits#10]
Is there a plan to upgrade these projects to .NET Core 2.1?

I've cloned the repo locally and would be interested in tackling that task, but I don't have the ability to create a branch.

**Comment by dseelinger** [comment]
You can fork it and use that for a while, but our team's project is currently 2.0 and we need to upgrade (probably in the next 3 weeks or so) before we can upgrade.

**Comment by dseelinger** [comment]
Should only be 2-3 weeks at a guess.

**Comment by ynauls** [comment]
I will take a look if we can add a .NET Core 2.1 version to the Nuget package without upgrading the code base.

**Comment by ynauls** [comment]
@sitwalkstand, the resolution to this issue has been published as a pre-release version (0.4.0-prerelease-1).  Please let us know if you run into any issues.

[Install-Package dotnet-fbit -Version 0.4.0-prerelease-1](https://www.nuget.org/packages/dotnet-fbit/0.4.0-prerelease-1)
